# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anton_beton/Desktop/projects/minishell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anton_beton/Desktop/projects/minishell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anton_beton/Desktop/projects/minishell/CMakeFiles /home/anton_beton/Desktop/projects/minishell//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anton_beton/Desktop/projects/minishell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minishell

# Build rule for target.
minishell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minishell
.PHONY : minishell

# fast build rule for target.
minishell/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/build
.PHONY : minishell/fast

#=============================================================================
# Target rules for targets named ft

# Build rule for target.
ft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft
.PHONY : ft

# fast build rule for target.
ft/fast:
	$(MAKE) $(MAKESILENT) -f Libft/CMakeFiles/ft.dir/build.make Libft/CMakeFiles/ft.dir/build
.PHONY : ft/fast

src/cmd_builtins/ft_cd.o: src/cmd_builtins/ft_cd.c.o
.PHONY : src/cmd_builtins/ft_cd.o

# target to build an object file
src/cmd_builtins/ft_cd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_cd.c.o
.PHONY : src/cmd_builtins/ft_cd.c.o

src/cmd_builtins/ft_cd.i: src/cmd_builtins/ft_cd.c.i
.PHONY : src/cmd_builtins/ft_cd.i

# target to preprocess a source file
src/cmd_builtins/ft_cd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_cd.c.i
.PHONY : src/cmd_builtins/ft_cd.c.i

src/cmd_builtins/ft_cd.s: src/cmd_builtins/ft_cd.c.s
.PHONY : src/cmd_builtins/ft_cd.s

# target to generate assembly for a file
src/cmd_builtins/ft_cd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_cd.c.s
.PHONY : src/cmd_builtins/ft_cd.c.s

src/cmd_builtins/ft_echo.o: src/cmd_builtins/ft_echo.c.o
.PHONY : src/cmd_builtins/ft_echo.o

# target to build an object file
src/cmd_builtins/ft_echo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_echo.c.o
.PHONY : src/cmd_builtins/ft_echo.c.o

src/cmd_builtins/ft_echo.i: src/cmd_builtins/ft_echo.c.i
.PHONY : src/cmd_builtins/ft_echo.i

# target to preprocess a source file
src/cmd_builtins/ft_echo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_echo.c.i
.PHONY : src/cmd_builtins/ft_echo.c.i

src/cmd_builtins/ft_echo.s: src/cmd_builtins/ft_echo.c.s
.PHONY : src/cmd_builtins/ft_echo.s

# target to generate assembly for a file
src/cmd_builtins/ft_echo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_echo.c.s
.PHONY : src/cmd_builtins/ft_echo.c.s

src/cmd_builtins/ft_env.o: src/cmd_builtins/ft_env.c.o
.PHONY : src/cmd_builtins/ft_env.o

# target to build an object file
src/cmd_builtins/ft_env.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_env.c.o
.PHONY : src/cmd_builtins/ft_env.c.o

src/cmd_builtins/ft_env.i: src/cmd_builtins/ft_env.c.i
.PHONY : src/cmd_builtins/ft_env.i

# target to preprocess a source file
src/cmd_builtins/ft_env.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_env.c.i
.PHONY : src/cmd_builtins/ft_env.c.i

src/cmd_builtins/ft_env.s: src/cmd_builtins/ft_env.c.s
.PHONY : src/cmd_builtins/ft_env.s

# target to generate assembly for a file
src/cmd_builtins/ft_env.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_env.c.s
.PHONY : src/cmd_builtins/ft_env.c.s

src/cmd_builtins/ft_exit.o: src/cmd_builtins/ft_exit.c.o
.PHONY : src/cmd_builtins/ft_exit.o

# target to build an object file
src/cmd_builtins/ft_exit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_exit.c.o
.PHONY : src/cmd_builtins/ft_exit.c.o

src/cmd_builtins/ft_exit.i: src/cmd_builtins/ft_exit.c.i
.PHONY : src/cmd_builtins/ft_exit.i

# target to preprocess a source file
src/cmd_builtins/ft_exit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_exit.c.i
.PHONY : src/cmd_builtins/ft_exit.c.i

src/cmd_builtins/ft_exit.s: src/cmd_builtins/ft_exit.c.s
.PHONY : src/cmd_builtins/ft_exit.s

# target to generate assembly for a file
src/cmd_builtins/ft_exit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_exit.c.s
.PHONY : src/cmd_builtins/ft_exit.c.s

src/cmd_builtins/ft_export.o: src/cmd_builtins/ft_export.c.o
.PHONY : src/cmd_builtins/ft_export.o

# target to build an object file
src/cmd_builtins/ft_export.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_export.c.o
.PHONY : src/cmd_builtins/ft_export.c.o

src/cmd_builtins/ft_export.i: src/cmd_builtins/ft_export.c.i
.PHONY : src/cmd_builtins/ft_export.i

# target to preprocess a source file
src/cmd_builtins/ft_export.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_export.c.i
.PHONY : src/cmd_builtins/ft_export.c.i

src/cmd_builtins/ft_export.s: src/cmd_builtins/ft_export.c.s
.PHONY : src/cmd_builtins/ft_export.s

# target to generate assembly for a file
src/cmd_builtins/ft_export.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_export.c.s
.PHONY : src/cmd_builtins/ft_export.c.s

src/cmd_builtins/ft_pwd.o: src/cmd_builtins/ft_pwd.c.o
.PHONY : src/cmd_builtins/ft_pwd.o

# target to build an object file
src/cmd_builtins/ft_pwd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_pwd.c.o
.PHONY : src/cmd_builtins/ft_pwd.c.o

src/cmd_builtins/ft_pwd.i: src/cmd_builtins/ft_pwd.c.i
.PHONY : src/cmd_builtins/ft_pwd.i

# target to preprocess a source file
src/cmd_builtins/ft_pwd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_pwd.c.i
.PHONY : src/cmd_builtins/ft_pwd.c.i

src/cmd_builtins/ft_pwd.s: src/cmd_builtins/ft_pwd.c.s
.PHONY : src/cmd_builtins/ft_pwd.s

# target to generate assembly for a file
src/cmd_builtins/ft_pwd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_pwd.c.s
.PHONY : src/cmd_builtins/ft_pwd.c.s

src/cmd_builtins/ft_unset.o: src/cmd_builtins/ft_unset.c.o
.PHONY : src/cmd_builtins/ft_unset.o

# target to build an object file
src/cmd_builtins/ft_unset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_unset.c.o
.PHONY : src/cmd_builtins/ft_unset.c.o

src/cmd_builtins/ft_unset.i: src/cmd_builtins/ft_unset.c.i
.PHONY : src/cmd_builtins/ft_unset.i

# target to preprocess a source file
src/cmd_builtins/ft_unset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_unset.c.i
.PHONY : src/cmd_builtins/ft_unset.c.i

src/cmd_builtins/ft_unset.s: src/cmd_builtins/ft_unset.c.s
.PHONY : src/cmd_builtins/ft_unset.s

# target to generate assembly for a file
src/cmd_builtins/ft_unset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cmd_builtins/ft_unset.c.s
.PHONY : src/cmd_builtins/ft_unset.c.s

src/environment/environ.o: src/environment/environ.c.o
.PHONY : src/environment/environ.o

# target to build an object file
src/environment/environ.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/environ.c.o
.PHONY : src/environment/environ.c.o

src/environment/environ.i: src/environment/environ.c.i
.PHONY : src/environment/environ.i

# target to preprocess a source file
src/environment/environ.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/environ.c.i
.PHONY : src/environment/environ.c.i

src/environment/environ.s: src/environment/environ.c.s
.PHONY : src/environment/environ.s

# target to generate assembly for a file
src/environment/environ.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/environ.c.s
.PHONY : src/environment/environ.c.s

src/environment/ft_getenv.o: src/environment/ft_getenv.c.o
.PHONY : src/environment/ft_getenv.o

# target to build an object file
src/environment/ft_getenv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_getenv.c.o
.PHONY : src/environment/ft_getenv.c.o

src/environment/ft_getenv.i: src/environment/ft_getenv.c.i
.PHONY : src/environment/ft_getenv.i

# target to preprocess a source file
src/environment/ft_getenv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_getenv.c.i
.PHONY : src/environment/ft_getenv.c.i

src/environment/ft_getenv.s: src/environment/ft_getenv.c.s
.PHONY : src/environment/ft_getenv.s

# target to generate assembly for a file
src/environment/ft_getenv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_getenv.c.s
.PHONY : src/environment/ft_getenv.c.s

src/environment/ft_setenv.o: src/environment/ft_setenv.c.o
.PHONY : src/environment/ft_setenv.o

# target to build an object file
src/environment/ft_setenv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_setenv.c.o
.PHONY : src/environment/ft_setenv.c.o

src/environment/ft_setenv.i: src/environment/ft_setenv.c.i
.PHONY : src/environment/ft_setenv.i

# target to preprocess a source file
src/environment/ft_setenv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_setenv.c.i
.PHONY : src/environment/ft_setenv.c.i

src/environment/ft_setenv.s: src/environment/ft_setenv.c.s
.PHONY : src/environment/ft_setenv.s

# target to generate assembly for a file
src/environment/ft_setenv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_setenv.c.s
.PHONY : src/environment/ft_setenv.c.s

src/environment/ft_unsetenv.o: src/environment/ft_unsetenv.c.o
.PHONY : src/environment/ft_unsetenv.o

# target to build an object file
src/environment/ft_unsetenv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_unsetenv.c.o
.PHONY : src/environment/ft_unsetenv.c.o

src/environment/ft_unsetenv.i: src/environment/ft_unsetenv.c.i
.PHONY : src/environment/ft_unsetenv.i

# target to preprocess a source file
src/environment/ft_unsetenv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_unsetenv.c.i
.PHONY : src/environment/ft_unsetenv.c.i

src/environment/ft_unsetenv.s: src/environment/ft_unsetenv.c.s
.PHONY : src/environment/ft_unsetenv.s

# target to generate assembly for a file
src/environment/ft_unsetenv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/environment/ft_unsetenv.c.s
.PHONY : src/environment/ft_unsetenv.c.s

src/error.o: src/error.c.o
.PHONY : src/error.o

# target to build an object file
src/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/error.c.o
.PHONY : src/error.c.o

src/error.i: src/error.c.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/error.c.i
.PHONY : src/error.c.i

src/error.s: src/error.c.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/error.c.s
.PHONY : src/error.c.s

src/execute/execute.o: src/execute/execute.c.o
.PHONY : src/execute/execute.o

# target to build an object file
src/execute/execute.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/execute.c.o
.PHONY : src/execute/execute.c.o

src/execute/execute.i: src/execute/execute.c.i
.PHONY : src/execute/execute.i

# target to preprocess a source file
src/execute/execute.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/execute.c.i
.PHONY : src/execute/execute.c.i

src/execute/execute.s: src/execute/execute.c.s
.PHONY : src/execute/execute.s

# target to generate assembly for a file
src/execute/execute.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/execute.c.s
.PHONY : src/execute/execute.c.s

src/execute/multi_cmd.o: src/execute/multi_cmd.c.o
.PHONY : src/execute/multi_cmd.o

# target to build an object file
src/execute/multi_cmd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/multi_cmd.c.o
.PHONY : src/execute/multi_cmd.c.o

src/execute/multi_cmd.i: src/execute/multi_cmd.c.i
.PHONY : src/execute/multi_cmd.i

# target to preprocess a source file
src/execute/multi_cmd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/multi_cmd.c.i
.PHONY : src/execute/multi_cmd.c.i

src/execute/multi_cmd.s: src/execute/multi_cmd.c.s
.PHONY : src/execute/multi_cmd.s

# target to generate assembly for a file
src/execute/multi_cmd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/multi_cmd.c.s
.PHONY : src/execute/multi_cmd.c.s

src/execute/single_cmd.o: src/execute/single_cmd.c.o
.PHONY : src/execute/single_cmd.o

# target to build an object file
src/execute/single_cmd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/single_cmd.c.o
.PHONY : src/execute/single_cmd.c.o

src/execute/single_cmd.i: src/execute/single_cmd.c.i
.PHONY : src/execute/single_cmd.i

# target to preprocess a source file
src/execute/single_cmd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/single_cmd.c.i
.PHONY : src/execute/single_cmd.c.i

src/execute/single_cmd.s: src/execute/single_cmd.c.s
.PHONY : src/execute/single_cmd.s

# target to generate assembly for a file
src/execute/single_cmd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/single_cmd.c.s
.PHONY : src/execute/single_cmd.c.s

src/execute/wait_children.o: src/execute/wait_children.c.o
.PHONY : src/execute/wait_children.o

# target to build an object file
src/execute/wait_children.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/wait_children.c.o
.PHONY : src/execute/wait_children.c.o

src/execute/wait_children.i: src/execute/wait_children.c.i
.PHONY : src/execute/wait_children.i

# target to preprocess a source file
src/execute/wait_children.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/wait_children.c.i
.PHONY : src/execute/wait_children.c.i

src/execute/wait_children.s: src/execute/wait_children.c.s
.PHONY : src/execute/wait_children.s

# target to generate assembly for a file
src/execute/wait_children.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/execute/wait_children.c.s
.PHONY : src/execute/wait_children.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/main.c.s
.PHONY : src/main.c.s

src/parsing/check_spec_char.o: src/parsing/check_spec_char.c.o
.PHONY : src/parsing/check_spec_char.o

# target to build an object file
src/parsing/check_spec_char.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/check_spec_char.c.o
.PHONY : src/parsing/check_spec_char.c.o

src/parsing/check_spec_char.i: src/parsing/check_spec_char.c.i
.PHONY : src/parsing/check_spec_char.i

# target to preprocess a source file
src/parsing/check_spec_char.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/check_spec_char.c.i
.PHONY : src/parsing/check_spec_char.c.i

src/parsing/check_spec_char.s: src/parsing/check_spec_char.c.s
.PHONY : src/parsing/check_spec_char.s

# target to generate assembly for a file
src/parsing/check_spec_char.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/check_spec_char.c.s
.PHONY : src/parsing/check_spec_char.c.s

src/parsing/parse.o: src/parsing/parse.c.o
.PHONY : src/parsing/parse.o

# target to build an object file
src/parsing/parse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/parse.c.o
.PHONY : src/parsing/parse.c.o

src/parsing/parse.i: src/parsing/parse.c.i
.PHONY : src/parsing/parse.i

# target to preprocess a source file
src/parsing/parse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/parse.c.i
.PHONY : src/parsing/parse.c.i

src/parsing/parse.s: src/parsing/parse.c.s
.PHONY : src/parsing/parse.s

# target to generate assembly for a file
src/parsing/parse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/parse.c.s
.PHONY : src/parsing/parse.c.s

src/parsing/tokenize.o: src/parsing/tokenize.c.o
.PHONY : src/parsing/tokenize.o

# target to build an object file
src/parsing/tokenize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/tokenize.c.o
.PHONY : src/parsing/tokenize.c.o

src/parsing/tokenize.i: src/parsing/tokenize.c.i
.PHONY : src/parsing/tokenize.i

# target to preprocess a source file
src/parsing/tokenize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/tokenize.c.i
.PHONY : src/parsing/tokenize.c.i

src/parsing/tokenize.s: src/parsing/tokenize.c.s
.PHONY : src/parsing/tokenize.s

# target to generate assembly for a file
src/parsing/tokenize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/parsing/tokenize.c.s
.PHONY : src/parsing/tokenize.c.s

src/redirections/redir_stdin.o: src/redirections/redir_stdin.c.o
.PHONY : src/redirections/redir_stdin.o

# target to build an object file
src/redirections/redir_stdin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/redirections/redir_stdin.c.o
.PHONY : src/redirections/redir_stdin.c.o

src/redirections/redir_stdin.i: src/redirections/redir_stdin.c.i
.PHONY : src/redirections/redir_stdin.i

# target to preprocess a source file
src/redirections/redir_stdin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/redirections/redir_stdin.c.i
.PHONY : src/redirections/redir_stdin.c.i

src/redirections/redir_stdin.s: src/redirections/redir_stdin.c.s
.PHONY : src/redirections/redir_stdin.s

# target to generate assembly for a file
src/redirections/redir_stdin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/redirections/redir_stdin.c.s
.PHONY : src/redirections/redir_stdin.c.s

src/redirections/redir_stdout.o: src/redirections/redir_stdout.c.o
.PHONY : src/redirections/redir_stdout.o

# target to build an object file
src/redirections/redir_stdout.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/redirections/redir_stdout.c.o
.PHONY : src/redirections/redir_stdout.c.o

src/redirections/redir_stdout.i: src/redirections/redir_stdout.c.i
.PHONY : src/redirections/redir_stdout.i

# target to preprocess a source file
src/redirections/redir_stdout.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/redirections/redir_stdout.c.i
.PHONY : src/redirections/redir_stdout.c.i

src/redirections/redir_stdout.s: src/redirections/redir_stdout.c.s
.PHONY : src/redirections/redir_stdout.s

# target to generate assembly for a file
src/redirections/redir_stdout.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/redirections/redir_stdout.c.s
.PHONY : src/redirections/redir_stdout.c.s

src/signals.o: src/signals.c.o
.PHONY : src/signals.o

# target to build an object file
src/signals.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/signals.c.o
.PHONY : src/signals.c.o

src/signals.i: src/signals.c.i
.PHONY : src/signals.i

# target to preprocess a source file
src/signals.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/signals.c.i
.PHONY : src/signals.c.i

src/signals.s: src/signals.c.s
.PHONY : src/signals.s

# target to generate assembly for a file
src/signals.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/signals.c.s
.PHONY : src/signals.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ft"
	@echo "... minishell"
	@echo "... src/cmd_builtins/ft_cd.o"
	@echo "... src/cmd_builtins/ft_cd.i"
	@echo "... src/cmd_builtins/ft_cd.s"
	@echo "... src/cmd_builtins/ft_echo.o"
	@echo "... src/cmd_builtins/ft_echo.i"
	@echo "... src/cmd_builtins/ft_echo.s"
	@echo "... src/cmd_builtins/ft_env.o"
	@echo "... src/cmd_builtins/ft_env.i"
	@echo "... src/cmd_builtins/ft_env.s"
	@echo "... src/cmd_builtins/ft_exit.o"
	@echo "... src/cmd_builtins/ft_exit.i"
	@echo "... src/cmd_builtins/ft_exit.s"
	@echo "... src/cmd_builtins/ft_export.o"
	@echo "... src/cmd_builtins/ft_export.i"
	@echo "... src/cmd_builtins/ft_export.s"
	@echo "... src/cmd_builtins/ft_pwd.o"
	@echo "... src/cmd_builtins/ft_pwd.i"
	@echo "... src/cmd_builtins/ft_pwd.s"
	@echo "... src/cmd_builtins/ft_unset.o"
	@echo "... src/cmd_builtins/ft_unset.i"
	@echo "... src/cmd_builtins/ft_unset.s"
	@echo "... src/environment/environ.o"
	@echo "... src/environment/environ.i"
	@echo "... src/environment/environ.s"
	@echo "... src/environment/ft_getenv.o"
	@echo "... src/environment/ft_getenv.i"
	@echo "... src/environment/ft_getenv.s"
	@echo "... src/environment/ft_setenv.o"
	@echo "... src/environment/ft_setenv.i"
	@echo "... src/environment/ft_setenv.s"
	@echo "... src/environment/ft_unsetenv.o"
	@echo "... src/environment/ft_unsetenv.i"
	@echo "... src/environment/ft_unsetenv.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/execute/execute.o"
	@echo "... src/execute/execute.i"
	@echo "... src/execute/execute.s"
	@echo "... src/execute/multi_cmd.o"
	@echo "... src/execute/multi_cmd.i"
	@echo "... src/execute/multi_cmd.s"
	@echo "... src/execute/single_cmd.o"
	@echo "... src/execute/single_cmd.i"
	@echo "... src/execute/single_cmd.s"
	@echo "... src/execute/wait_children.o"
	@echo "... src/execute/wait_children.i"
	@echo "... src/execute/wait_children.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parsing/check_spec_char.o"
	@echo "... src/parsing/check_spec_char.i"
	@echo "... src/parsing/check_spec_char.s"
	@echo "... src/parsing/parse.o"
	@echo "... src/parsing/parse.i"
	@echo "... src/parsing/parse.s"
	@echo "... src/parsing/tokenize.o"
	@echo "... src/parsing/tokenize.i"
	@echo "... src/parsing/tokenize.s"
	@echo "... src/redirections/redir_stdin.o"
	@echo "... src/redirections/redir_stdin.i"
	@echo "... src/redirections/redir_stdin.s"
	@echo "... src/redirections/redir_stdout.o"
	@echo "... src/redirections/redir_stdout.i"
	@echo "... src/redirections/redir_stdout.s"
	@echo "... src/signals.o"
	@echo "... src/signals.i"
	@echo "... src/signals.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

